version: "3.5"

services:
  service:
    image: veupathdb/dataset-access-service:${SERVICE_TAG:-latest}
    environment:
      SERVER_PORT: ${SERVER_PORT:-80}

      # User authentication salt
      AUTH_SECRET_KEY: ${AUTH_SECRET_KEY?required}

      # LDAP
      LDAP_SERVER: ${LDAP_SERVER?required}
      ORACLE_BASE_DN: ${ORACLE_BASE_DN?required}

      # Application DB
      APP_DB_TNS_NAME: ${APP_DB_TNS_NAME?required}
      APP_DB_USER: ${APP_DB_USER?required}
      APP_DB_PASS: ${APP_DB_PASS?required}
      APP_DB_POOL_SIZE: 20

      # Account DB
      ACCT_DB_TNS_NAME: ${ACCT_DB_TNS_NAME?required}
      ACCT_DB_USER: ${ACCT_DB_USER?required}
      ACCT_DB_PASS: ${ACCT_DB_PASS?required}
      ACCT_DB_POOL_SIZE: 20

      # EMAIL STUFF
      ENABLE_EMAIL: !!str true
      SMTP_HOST: ${SMTP_HOST?required}
      SUPPORT_EMAIL: ${SUPPORT_EMAIL?required}
      EMAIL_DEBUG: !!str false

      # Site stuff
      SITE_URL: # https://clinepidb.org/ce
      REGISTRATION_PATH: /app/user/registration
      APPLICATION_PATH: /app/study-access

    networks:
    - traefik
    - monitoring-ext
    labels:
    - "traefik.http.routers.${TRAEFIK_ROUTER:-das-dev}.rule=Host(`${TRAEFIK_HOST:-das-dev.local.apidb.org}`)"
    - "traefik.http.routers.${TRAEFIK_ROUTER:-das-dev}.tls=true"
    - "traefik.http.routers.${TRAEFIK_ROUTER:-das-dev}.entrypoints=local"
    - "traefik.http.services.${TRAEFIK_ROUTER:-das-dev}.loadbalancer.server.port=80"
    - "traefik.docker.network=traefik"
    - "com.centurylinklabs.watchtower.enable=${SERVICE_WATCHTOWER:-false}"
    - "prometheus-scrape.enabled=true"


networks:
  traefik:
    external: true
  monitoring-ext:
    external: true
