version: "3.8"

services:
  service:
    build:
      dockerfile: Dockerfile
      context: .
    environment:
      SERVER_PORT: 80

      # User authentication salt
      AUTH_SECRET_KEY:

      # Application DB
      APP_DB_TNS_NAME:
      APP_DB_USER:
      APP_DB_PASS:

      # Account DB
      ACCT_DB_TNS_NAME:
      ACCT_DB_USER:
      ACCT_DB_PASS:

      # User DB
      USER_DB_TNS_NAME:
      USER_DB_USER:
      USER_DB_PASS:

      # LDAP
      LDAP_SERVER:
      ORACLE_BASE_DN:
    ports:
    - 8088:80
    networks:
    - traefik
    labels:
    - "traefik.http.routers.dataset-access-service-dev.rule=Host(`dataset-access-service-dev.local.apidb.org`)"
    - "traefik.http.routers.dataset-access-service-dev.tls=true"
    - "traefik.http.routers.dataset-access-service-dev.entrypoints=local"
    - "traefik.http.services.dataset-access-service-dev.loadbalancer.server.port=80"
networks:
  traefik:
    external: true
