= Database Updates

The following modifications are required for this service to operate.

== Account DB

=== `studyaccess.approval_status`

New controlled vocabulary table for end user dataset request approval status.

.Create Table
[source, sql]
----
CREATE TABLE studyaccess.approval_status
(
  approval_status_id NUMBER(1) GENERATED AS IDENTITY
    CONSTRAINT approval_status_pk PRIMARY KEY,
  name               VARCHAR2(24) NOT NULL
)
----

.Populate Table
[source, sql]
----
INSERT INTO studyaccess.approval_status (name) VALUES ('approved');
INSERT INTO studyaccess.approval_status (name) VALUES ('requested');
INSERT INTO studyaccess.approval_status (name) VALUES ('denied');
----

.Grant Access
[source, sql]
----
GRANT SELECT ON studyaccess.approval_status TO COMM_WDK_W;
----

=== `studyaccess.restriction_level`

New controlled vocabulary table for end user dataset request restriction level.

.Create Table
[source, sql]
----
CREATE TABLE studyaccess.restriction_level
(
  restriction_level_id NUMBER(1) GENERATED AS IDENTITY
    CONSTRAINT restriction_level_pk PRIMARY KEY,
  name                 VARCHAR2(24) UNIQUE NOT NULL
)
----

.Populate Table
[source, sql]
----
INSERT INTO studyaccess.restriction_level (name) VALUES ('public');
INSERT INTO studyaccess.restriction_level (name) VALUES ('limited');
INSERT INTO studyaccess.restriction_level (name) VALUES ('protected');
INSERT INTO studyaccess.restriction_level (name) VALUES ('controlled');
INSERT INTO studyaccess.restriction_level (name) VALUES ('admin');
----

.Grant Access
[source, sql]
----
GRANT SELECT ON studyaccess.restriction_level TO COMM_WDK_W;
----

=== `studyaccess.staff`

New table tracking site staff.

.Create Table
[source, sql]
----
CREATE TABLE studyaccess.staff
(
  staff_id NUMBER(8) GENERATED AS IDENTITY CONSTRAINT staff_pk PRIMARY KEY,
  user_id NUMBER(12) NOT NULL UNIQUE,
  is_owner NUMBER(1) DEFAULT 0 NOT NULL CHECK ( is_owner = 0 OR is_owner = 1 )
)
----

.Populate Table
[source, sql]
----
INSERT INTO studyaccess.staff (user_id, is_owner) VALUES (48, 1);
INSERT INTO studyaccess.staff (user_id, is_owner) VALUES (376, 1);
INSERT INTO studyaccess.staff (user_id, is_owner) VALUES (220902410, 1);
INSERT INTO studyaccess.staff (user_id, is_owner) VALUES (295652793, 1);
INSERT INTO studyaccess.staff (user_id, is_owner) VALUES (276765373, 1);
----

.Grant Access
[source, sql]
----
GRANT SELECT, INSERT, UPDATE, DELETE ON studyaccess.staff TO COMM_WDK_W;
----

=== `studyaccess.providers`

New table tracking dataset providers.

.Create Table
[source, sql]
----
CREATE TABLE studyaccess.providers
(
  provider_id NUMBER(8) GENERATED AS IDENTITY
    CONSTRAINT providers_pk PRIMARY KEY,
  user_id NUMBER(12) NOT NULL,
  is_manager NUMBER(1) DEFAULT 0 NOT NULL
    CHECK ( is_manager = 0 OR is_manager = 1 ),
  dataset_id VARCHAR2(15) NOT NULL,
  CONSTRAINT provider_user_ds_uq UNIQUE (user_id, dataset_id)
)
----

.Grant Access
[source, sql]
----
GRANT SELECT, INSERT, UPDATE, DELETE ON studyaccess.providers TO COMM_WDK_W;
----

=== `studyaccess.validdatasetuser`

Modifications to the existing dataset end user.

.1. Add New Columns
[source, sql]
----
ALTER TABLE studyaccess.validdatasetuser
  ADD restriction_level_id NUMBER(1)
    REFERENCES studyaccess.restriction_level (restriction_level_id);
ALTER TABLE studyaccess.validdatasetuser
  ADD approval_status_id NUMBER(1)
    REFERENCES studyaccess.approval_status (approval_status_id);
----

.2. Copy Values
[source, sql]
----
UPDATE
  studyaccess.validdatasetuser v
SET
  restriction_level_id = (
    SELECT restriction_level_id
    FROM studyaccess.restriction_level
    WHERE name = v.restriction_level
  );
UPDATE
  studyaccess.validdatasetuser v
SET
  approval_status_id = (
    SELECT approval_status_id
    FROM studyaccess.approval_status
    WHERE
      name = (
        decode(approval_status,
          0, 'approved',
          1, 'requested',
          2, 'denied',
          'approved'
        )
      )
  );
----

.3. Lock down new columns
[source, sql]
----
ALTER TABLE studyaccess.validdatasetuser
  MODIFY (restriction_level_id NOT NULL);
ALTER TABLE studyaccess.validdatasetuser
  MODIFY (approval_status_id NOT NULL);
----

.4. Drop old columns
[source, sql]
----
ALTER TABLE studyaccess.validdatasetuser
  DROP COLUMN restriction_level;
ALTER TABLE studyaccess.validdatasetuser
  DROP COLUMN approval_status;
----

.5. Add new approval denial column
[source, sql]
----
ALTER TABLE studyaccess.validdatasetuser
  ADD denial_reason VARCHAR2(4000);
----
